_target_: models.vit_module.VitModule

model_name: "google/vit-base-patch16-224-in21k"

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.00001
  weight_decay: 0.01

scheduler:
  null
  # _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  # _partial_: true
  # T_max: ${trainer.max_epochs}
  # verbose: false
# scheduler:
#   _target_: torch.optim.lr_scheduler.LinearLR
#   _partial_: true
#   start_factor: 0.1
#   end_factor: 1.0
#   total_iters: 2
#   verbose: true
